language: rust

rust:
  - nightly

cache: cargo

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source ~/.cargo/env
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - cargo install-update -a

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

  addons:
    apt:
      packages:
        - nasm

script:
  - make
