[package]
name = "infinity_os"
version = "0.1.0"
authors = [
    "Gil Mendes <gil00mendes@gmail.com>",
    "Ivo Ribeiro <ivolopesribeiro15@gmail.com>"
]

[lib]
crate-type = ["staticlib"]

[dependencies]
bit_field = "0.7.0"
bitflags = "0.7.0"
multiboot2 = "0.1.0"
rlibc = "0.1.4"
spin = "0.3.4"
volatile = "0.1.0"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "0.2.2"

[dependencies.x86]
default-features = false
version = "0.8.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
